CroW_HOME = "/mydata/QIK-IR-ClipCap/ML_Models/CroW"
PROTOTXT_PATH = CroW_HOME + "/vgg/VGG_ILSVRC_16_pool5.prototxt"
CAFFE_MODEL_PATH = CroW_HOME + "/vgg/VGG_ILSVRC_16_layers.caffemodel"
CROW_FEATURES_PATH = CroW_HOME + "/data/crow_features"
CROW_IMAGE_DIR = "/mydata/apache-tomcat/webapps/QIK_Image_Data/"